addons:
  code_climate:
    repo_token: d1544b1829d59ce219bd65a2f4a696b8940969d9f5f1790da55d5929357e4b03
language: ruby
rvm:
  - 1.8.7 
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: 1.9.2
    - rvm: jruby
    - rvm: rbx